#!/usr/bin/env bash
# Generate .env for worktree-isolated Docker services.
# Called by: make start-worktree
#
# Slot assignment: deterministic hash of directory basename.
# Override with: GAIA_SLOT=N make start-worktree
# Developer identity: derived from $USER in docker-compose (see ADR-001)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/worktree-port-conflicts.sh
source "$SCRIPT_DIR/lib/worktree-port-conflicts.sh"

WORKTREE_DIR="$(pwd)"
BASENAME="$(basename "$WORKTREE_DIR")"
BRANCH="$(git branch --show-current 2>/dev/null)"
# Empty branch means detached HEAD
if [[ -z "$BRANCH" ]]; then
  BRANCH="detached"
fi

# --- Derive branch tag ---
# Strip known type prefixes, then replace any remaining slashes with dashes
# (handles branches like spike/foo → spike-foo, keeping Docker names valid)
TAG="$(echo "$BRANCH" | sed -E 's#^(feature|fix|chore|hotfix|release)/##; s#/#-#g')"
# Truncate to 30 chars for Docker name limits
TAG="${TAG:0:30}"
# main/master → empty tag (use defaults)
if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
  TAG=""
fi
# detached HEAD in worktree → use basename for unique naming
if [[ "$BRANCH" == "detached" && "$BASENAME" != "gaia-free" ]]; then
  TAG="${BASENAME:0:30}"
fi

# --- Compute slot ---
# Priority: 1) GAIA_SLOT env var, 2) persisted slot in existing .env, 3) hash of basename
if [[ "$BASENAME" == "gaia-free" ]]; then
  SLOT=0
elif [[ -n "${GAIA_SLOT:-}" ]]; then
  SLOT="$GAIA_SLOT"
elif [[ -f .env ]] && grep -q "^GAIA_SLOT=" .env 2>/dev/null; then
  SLOT=$(grep "^GAIA_SLOT=" .env | cut -d= -f2)
else
  SLOT=$(printf '%s' "$BASENAME" | cksum | awk '{print ($1 % 9) + 1}')
fi

# --- Check for port conflicts and bump slot if needed ---
# Local daemon → lsof on the host. Remote daemon (DOCKER_HOST=ssh://… etc.) →
# host lsof can't see desktop-bound ports; ask the daemon's docker ps instead.
_remote_daemon() {
  case "${DOCKER_HOST:-}" in
    ""|unix://*) return 1 ;;
    *) return 0 ;;
  esac
}
if command -v docker >/dev/null 2>&1; then
  _docker_ports_cache="$(
    {
      docker ps -a --filter "status=running" --format '{{.Ports}}'
      docker ps -a --filter "status=created" --format '{{.Ports}}'
    } 2>/dev/null || true
  )"
else
  _docker_ports_cache=""
fi
if _remote_daemon; then
  _port_in_use() {
    printf '%s\n' "$_docker_ports_cache" | grep -qE "(^|, )[0-9.:]*:$1->"
  }
else
  _port_in_use() {
    printf '%s\n' "$_docker_ports_cache" | grep -qE "(^|, )[0-9.:]*:$1->" \
      || lsof -iTCP:"$1" -sTCP:LISTEN -t >/dev/null 2>&1
  }
fi

MAX_ATTEMPTS=9
for (( _attempt=0; _attempt < MAX_ATTEMPTS; _attempt++ )); do
  _bp=$((8000 + SLOT * 10))
  _fp=$((3000 + SLOT))
  _sp=$((8001 + SLOT * 10))
  if _port_in_use "$_bp" || _port_in_use "$_fp" || _port_in_use "$_sp" || ! gaia_worktree_port_conflicts_report "$_bp" "$_fp" "$_sp" >&2; then
    echo "⚠ Slot ${SLOT} has port conflict, trying next slot..." >&2
    SLOT=$(( (SLOT % 9) + 1 ))
  else
    break
  fi
done

# --- Sentry release tag ---
GIT_SHA="$(git rev-parse --short=7 HEAD 2>/dev/null || echo 'unknown')"
SENTRY_RELEASE="${TAG:-main}@${GIT_SHA}"

# --- Derive names ---
SUFFIX="${TAG:+-$TAG}"  # "-ref-image-pipeline" or ""
BACKEND_PORT=$((8000 + SLOT * 10))
FRONTEND_PORT=$((3000 + SLOT))
STT_PORT=$((8001 + SLOT * 10))

# --- Write .env ---
cat > .env <<EOF
# Auto-generated by scripts/worktree-env.sh — $(date -Iseconds)
# Worktree: ${WORKTREE_DIR}
# Branch: ${BRANCH}
# Slot: ${SLOT}
#
# Re-generate: make worktree-env
# Override slot: GAIA_SLOT=N make worktree-env

GAIA_SLOT=${SLOT}
GAIA_BRANCH_TAG=${TAG:-latest}
GAIA_IMAGE_TAG=${TAG:-latest}

# Container names (branch-based for readability in docker ps)
BACKEND_CONTAINER_NAME=gaia-backend${SUFFIX}
FRONTEND_CONTAINER_NAME=gaia-frontend${SUFFIX}
IMAGE_WORKER_CONTAINER_NAME=gaia-image-worker${SUFFIX}
STT_CONTAINER_NAME=gaia-stt${SUFFIX}
# Shared infrastructure (no suffix - all worktrees use the same instance)
RABBITMQ_CONTAINER_NAME=gaia-rabbitmq

# Host ports (slot-based to avoid collisions)
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
STT_PORT=${STT_PORT}

# Sentry observability (branch + commit for worktree segmentation)
SENTRY_RELEASE=${SENTRY_RELEASE}
VITE_SENTRY_RELEASE=${SENTRY_RELEASE}
SENTRY_BRANCH=${TAG:-main}
VITE_GAIA_BRANCH_TAG=${TAG:-main}

# Frontend: use Vite proxy instead of direct backend calls (avoids CORS issues)
VITE_API_BASE_URL=
EOF

echo "✓ Generated .env for slot ${SLOT} (branch: ${BRANCH})"
echo "  Backend:  http://localhost:${BACKEND_PORT}"
echo "  Frontend: http://localhost:${FRONTEND_PORT}"
echo "  STT:      http://localhost:${STT_PORT}"
